site_name: 
site_description: 
site_favicon: favicon.ico
repo_url: 
edit_uri: 
copyright: 
google_analytics: ['UA-54096005-4', 'auto']
theme: cinder
extra_css:
  - css/extra.css
pages:
  - Home: index.md
